import "dotenv/config";
import express from "express";
import cors from "cors";
import authRoutes from "./routes/auth.js";
import productRoutes from "./routes/products.js";
import salesRoutes from "./routes/sales.js";
import masterRoutes from "./routes/master.js";
import dashboardRoutes from "./routes/dashboard.js";
import printerRoutes from "./routes/printer.js";
import returnRoutes from "./routes/returns.js";
import branchRoutes from "./routes/branches.js";
import auditRoutes from "./routes/audit.js";
const app=express();
app.use(cors({origin:process.env.CLIENT_URL||"http://localhost:5173"}));
app.use(express.json({limit:"2mb"}));
app.get("/api/health",(req,res)=>res.json({status:"ok",service:"retailflow-pos-api"}));
app.use("/api/auth",authRoutes);
app.use("/api/products",productRoutes);
app.use("/api/sales",salesRoutes);
app.use("/api/master",masterRoutes);
app.use("/api/dashboard",dashboardRoutes);
app.use("/api/printer",printerRoutes);
app.use("/api/returns",returnRoutes);
app.use("/api/branches",branchRoutes);
app.use("/api/audit",auditRoutes);
app.use((req,res)=>res.status(404).json({message:"Route not found."}));
app.listen(process.env.PORT||5000,()=>console.log(`POS API running on ${process.env.PORT||5000}`));
